[book]
title = "mdBook中文指南"
description = "Create book from markdown files. Like Gitbook but implemented in Rust"
authors = ["Mathieu David", "Michael-F-Bryan"]
language = "zh"
multilingual = false

[output.html]
additional-css = ["theme/style3.css"]
git-repository-url = "https://github.com/widaT/mdbook"
edit-url-template = "https://github.com/widaT/mdbook/edit/master/{path}"

[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = false
level = 1

[rust]
edition = "2018"
